// THE DOCUMENTS print-check KNOWS: how each is rendered, what it prints on, and how its rows are read.
//
// The two estimate layouts and the multi-job sheet are components and render directly. The inspection sheet is
// written inline inside its screen, and the multi-job sheet's figures come from functions inside EstimateGenerate -
// both are CUT from the source between markers (lib/sources.cut) until they are extracted.
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { Refusal, slash } from './env.mjs';
import { cut, letterheadRegion, readSource } from './sources.mjs';
import { pickEstimate, pickExternalInspection, pickExternalInspectionStress, pickInspection, pickInspectionNoLetterhead, pickInspectionStress, pickMultiJob, pickTestingReport, pickTestingReportNoLetterhead, pickTestingReportStress } from './data.mjs';

const EG = 'src/components/EstimateGenerate.tsx';

const head = (root, id) => `// GENERATED by scripts/print-check for one run - not edited, not kept.
import React from 'react';
import { createRoot } from 'react-dom/client';
import { MemoryRouter } from 'react-router-dom';
import './harness.css';
import { triggerUniversalPrint } from '${slash(root)}/src/lib/printUtils';
import DATA_ from './${id}.json';
const D: any = DATA_;
let EXPECTED: any = {};
(window as any).__printCheck = { state: 'rendering' };
`;

const mount = `createRoot(document.getElementById('root')!).render(<MemoryRouter><Doc /></MemoryRouter>);\n`;

/** Whether this tree's print path measures sheets and warns before the dialog (G66), or opens it on load. */
const measuresBeforePrinting = root => readSource(root, 'src/lib/printUtils.ts').includes('export function measureSheets');

/**
 * THE APP'S OWN PRINT PATH, RUN FOR REAL.
 *
 * `measured` (G66 onward): triggerUniversalPrint is handed a stand-in window whose document IS this page, so the app
 * writes the print window into it, measures the sheets itself, and then either calls print() or shows its warning -
 * and which it did is recorded, along with what the sheets said on screen before.
 *
 * `captured` (older commits): the print window's HTML is captured, its print-on-load script dropped, and written into
 * this page. Those commits had no warning to check.
 */
/** Whether this tree's sheets carry the name the warning uses (G67). Before it, the warning numbers sheets. */
const namesSheets = root => readSource(root, 'src/components/LetterheadHeader.tsx').includes('data-sheet-name');

/**
 * Whether this tree cuts the inspection deck by MEASURED HEIGHT (O64 step 2) or at a constant.
 *
 * ⚠ THE HOOK IS NOT IN THE CUT BLOCK, AND IT CANNOT BE. It has to run before the screen's `if (!activeAgency)`
 * early return or React throws #310 on that branch (scripts/admin/hooks-after-return.js), and the cut starts below
 * that return. So it is reconstructed here, exactly as the component calls it. On a commit that still cuts at a
 * constant, the chunking is inside the cut block and nothing is added.
 */
const paginatesByHeight = root => existsSync(join(root, 'src/lib/useMeasuredRowChunks.ts'));

/**
 * Whether this tree has the shared MR grouping (AUDIT G104), which is what orders the multi-job sheet's columns.
 *
 * ⚠ ON A TREE WITHOUT IT THE OLD SUBSTITUTION IS USED, AND THAT IS THE POINT. Before G104 the grouping was an inline
 * loop inside EstimateGenerate that did not sort, so `{ [mrNo]: jobs }` over the list in the order the read
 * returned it reproduces exactly what that commit printed. After it, the real function is imported. That is what lets `--compare` show the
 * columns reordering instead of reporting "nothing changed on paper".
 */
const sharesMrGrouping = root => existsSync(join(root, 'src/lib/mrGrouping.ts'));

/**
 * Whether this tree asks the HV S.E./DPC question for aluminium only (AUDIT G105). Before it, the inspection sheet
 * asked it of every winding and printed "Not S.E."; after it the field is aluminium-only, the label reads
 * "DPC (not S.E.)" and a copper row prints "-". The cut block needs the shared rule, so the import is added only
 * where the module exists and `--compare` still builds the commits before it.
 */
const asksHvSeForAluminiumOnly = root => existsSync(join(root, 'src/lib/hvSeConductor.ts'));

const runtime = (container, orientation, root) => { const measured = measuresBeforePrinting(root); return `
const w: any = window;
const sleep = (ms: number) => new Promise(r => setTimeout(r, ms));
(async () => {
  try {
    const t0 = Date.now();
    const lh = !!(D.agency && D.agency.letterheadUrl && (D.agency.letterheadMode === 'full_a4' || !D.agency.letterheadMode));
    let letterhead = lh ? 'pending' : 'none configured';
    for (;;) {
      const pages = document.querySelectorAll('.a4-print-page');
      const imgs = Array.from(document.querySelectorAll('.a4-print-page img')) as HTMLImageElement[];
      if (pages.length && (!lh || (imgs.length === pages.length && imgs.every(i => i.complete && i.naturalWidth > 0)))) { if (lh) letterhead = 'rendered'; break; }
      if (Date.now() - t0 > 30000) { if (!pages.length) throw new Error('no sheet rendered within 30s'); letterhead = 'NOT RENDERED within 30s'; break; }
      await sleep(200);
    }
    await (document as any).fonts.ready;
    await sleep(1200);
    ${measured ? `
    // The on-screen bars measure 400ms after the sheets settle. Read them only once every sheet says it has measured -
    // a number read before that is a zero nobody computed.
    for (const t2 = Date.now(); ; await sleep(100)) {
      const states = Array.from(document.querySelectorAll('.a4-print-page')).map(p => p.getAttribute('data-cutoff-state'));
      if (states.length && states.every(s => s === 'measured')) break;
      if (Date.now() - t2 > 20000) throw new Error('the sheets never reported their cut-off measurement (data-cutoff-state: ' + states.join(', ') + ')');
    }
    await sleep(800);
    ` : ''}
    const screenCutoffs = Array.from(document.querySelectorAll('.a4-print-page')).map((p: any) => ({
      bottomMm: Number(p.getAttribute('data-cutoff-bottom-mm') || 0), rightMm: Number(p.getAttribute('data-cutoff-right-mm') || 0) }));
    ${measured ? `
    // Held here so print-check can picture the sheets as the operator sees them in the app, bars and all.
    w.__printCheck = { state: 'screen' };
    for (const t3 = Date.now(); !w.__printCheckGo && Date.now() - t3 < 30000; ) await sleep(100);
    ` : ''}
    const realOpen = window.open;
    let flow = '${measured ? 'measured' : 'captured'}', autoPrinted = false, warningLines: string[] = [], printMs = 0;
    ${measured ? `
    (window as any).open = () => ({ document, focus() {}, print() { autoPrinted = true; } });
    const tPrint = performance.now();
    await triggerUniversalPrint('${container}', 'print-check', 'print-check.pdf', '${orientation}');
    printMs = Math.round(performance.now() - tPrint);
    window.open = realOpen;
    await sleep(900);
    const warning = document.getElementById('print-cutoff-warning');
    warningLines = warning ? Array.from(warning.querySelectorAll('li')).map(li => String(li.textContent)) : [];
    if (!document.querySelector('#${container}')) throw new Error('the print window received nothing');
    ` : `
    let captured = '';
    (window as any).open = () => ({ document: { open() {}, write(s: string) { captured += s; }, close() {} } });
    await triggerUniversalPrint('${container}', 'print-check', 'print-check.pdf', '${orientation}');
    window.open = realOpen;
    if (captured.indexOf('${container}') === -1) throw new Error('the print window received nothing');
    document.open(); document.write(captured.replace(/<script>[\\s\\S]*?<\\/script>/g, '')); document.close();
    const t1 = Date.now();
    for (;;) {
      const imgs = Array.from(document.images);
      const links = Array.from(document.querySelectorAll('link[rel="stylesheet"]')) as HTMLLinkElement[];
      if (imgs.every(i => i.complete) && links.every(l => l.sheet)) break;
      if (Date.now() - t1 > 15000) break;
      await sleep(100);
    }
    `}
    await sleep(500);
    const sheetNames = Array.from(document.querySelectorAll('.a4-print-page')).map(p => p.getAttribute('data-sheet-name'));
    w.__printCheck = { state: 'ready', letterhead, expected: EXPECTED, sheets: document.querySelectorAll('.a4-print-page').length,
      flow, screenCutoffs, autoPrinted, warningLines, printMs, sheetNames, named: ${namesSheets(root)} };
  } catch (e: any) {
    w.__printCheck = { state: 'error', message: String((e && e.stack) || e) };
  }
})();
`; };

const estimateSource = root => {
  const s = readSource(root, 'src/components/SingleJobEstimateReport.tsx');
  const a = s.indexOf('export default function SingleJobEstimateReport');
  return (a < 0 ? s : s.slice(a)) + letterheadRegion(root);
};

/** Both estimate layouts: the same component, a job whose tender prices it itemised, and one priced at a fixed rate. */
const estimate = (id, model, title) => ({
  id, title, kind: 'estimate', container: 'printable-estimate-container', orientation: 'portrait',
  select: live => pickEstimate(live, model),
  generate(root) {
    const r = slash(root);
    const orderRef = existsSync(join(root, 'src/lib/orderReference.ts'));   // G63; older commits have no such prop
    const entry = head(root, id) + `
import * as SJER from '${r}/src/components/SingleJobEstimateReport';
import * as AC from '${r}/src/lib/AgencyContext';
${orderRef ? `import { orderReferenceFor } from '${r}/src/lib/orderReference';` : ''}
const Estimate: any = (SJER as any).default;
function Doc(): any {
  const job = D.job, at = D.at, agency = D.agency;
  const est = (SJER as any).buildSingleJobEstimateData(job, agency, at, D.ext, D.int);
  EXPECTED = { rows: est.physicalItems.length + est.internalItems.length + est.labourItems.length };
  const extra: any = {};
  ${orderRef ? 'extra.orderRef = orderReferenceFor((AC as any).atResolutionForJob(job, D.ats), job.jobNo);' : ''}
  return (
    <div id="printable-estimate-container" className="space-y-6 print:space-y-0">
      <Estimate job={job} agency={agency} atMaster={at} externalData={D.ext} internalData={D.int} letterDateText={D.letterDate} {...extra} />
    </div>
  );
}
` + mount + runtime('printable-estimate-container', 'portrait', root);
    return { entry, coverageText: estimateSource(root) };
  },
});

const multiJob = {
  id: 'multi-job', title: 'Multi-job estimate sheet', kind: 'multi-job', container: 'printable-estimate-container', orientation: 'portrait',
  select: live => pickMultiJob(live),
  generate(root) {
    const r = slash(root);
    const grouped = sharesMrGrouping(root);
    // THE SHEET'S FIGURES COME FROM EstimateGenerate'S OWN FUNCTIONS, CUT FROM ITS SOURCE. Re-implementing them here
    // would be a second pricing path - the defect G8 removed from this very sheet.
    const wrapper = cut(root, EG, "the multi-job sheet's pricing wrapper (getJobFullEstimate)",
      '  const getJobFullEstimate = (job: any) => {', '  const calculateJobTotal = (job: any) => {', ['getJobFullEstimatePure(']);
    const builders = cut(root, EG, "the multi-job sheet's data (builderLineFor, buildMultiJobData)",
      '  const estimateCache = new Map<string, any>();', '  // Helper to evaluate a job against Clause 4.0 Circle Estimate Power Limit',
      ['const builderLineFor = (', 'const buildMultiJobData = (mr: string) => {']);
    const sheet = readSource(root, 'src/components/MultiJobEstimateSheet.tsx');
    const entry = head(root, 'multi-job') + `
import { MultiJobEstimateSheet } from '${r}/src/components/MultiJobEstimateSheet';
import * as SJER from '${r}/src/components/SingleJobEstimateReport';
import * as AC from '${r}/src/lib/AgencyContext';
import * as estimateCalc from '${r}/src/lib/estimateCalc';
import * as scheduleItemMap from '${r}/src/lib/scheduleItemMap';
${grouped ? `import { groupJobsByMr } from '${r}/src/lib/mrGrouping';` : ''}
const { classifyWindingMaterial } = SJER as any;
const { getEstimateMasterForCore, atForJob } = AC as any;
const { getJobFullEstimate: getJobFullEstimatePure, isGpJob } = estimateCalc as any;
// Whichever of these the commit's cut code uses; the other is simply undefined.
const { lineForMasterRow, builderCodeForMasterRow } = scheduleItemMap as any;
function multiJobData(): any {
  const activeAgency = D.agency, atMasters = D.ats, activeAtMaster = D.at;
  const externalInspMap = D.ext, internalInspMap = D.int;
  // ⚠ THE APP'S OWN GROUPING, IMPORTED - NOT A SUBSTITUTE (AUDIT G104). Substituting it reproduced the column order
  // faithfully AND was blind to any fix of it: this comparison reported "nothing changed on paper" for a change that
  // reorders every column, because the substitute replaced the very expression that carried the defect. A check that
  // cannot see its subject is this project's opening pattern; that was its first appearance inside the print harness.
  // D.jobs arrives in the order the read returned it, as the app receives it, so what prints is what the app computes.
  const mrGroups: Record<string, any[]> = ${grouped ? 'groupJobsByMr(D.jobs)' : '{ [D.mrNo]: D.jobs }'};
  const estimableJobs = (mr: string) => (mrGroups[mr] || []).filter((j: any) => !isGpJob(j));
  const refNoText = D.refNo, currentSelectedDivision = D.division, signedByText = D.signedBy;
${wrapper}
${builders}
  return buildMultiJobData(D.mrNo);
}
function Doc(): any {
  const data = multiJobData();
  EXPECTED = { rowsPerSheet: data.items.length, columns: data.columns.length };
  return (
    <div id="printable-estimate-container" className="space-y-6 print:space-y-0">
      <MultiJobEstimateSheet agency={D.agency} data={data} />
    </div>
  );
}
` + mount + runtime('printable-estimate-container', 'portrait', root);
    const a = sheet.indexOf('export function MultiJobEstimateSheet');
    return { entry, coverageText: (a < 0 ? sheet : sheet.slice(a)) + letterheadRegion(root) };
  },
};

/** The internal inspection sheet, on live rows or on the stress rows that produced O58 - the same generation. */
const inspection = (id, title, select) => ({
  id, title, kind: 'inspection', container: 'printable-internal-inspection-sheet', orientation: 'landscape',
  select,
  generate(root) {
    const r = slash(root);
    const file = 'src/components/InternalInspection.tsx';
    const hvSeAlOnly = asksHvSeForAluminiumOnly(root);
    // The whole print branch, from the scrap note it prints to the end of `if (isPrintOpen && selectedMrNo)`.
    const block = cut(root, file, 'the internal inspection sheet',
      '  const scrapJobs = mrJobs.filter(', '\n  return (\n    <div className="space-y-6 print:space-y-0">',
      ['if (isPrintOpen && selectedMrNo) {', '<PrintableA4Page', '</PrintableA4Page>']);
    const hv = (readSource(root, file).match(/const hvCoilsPerLimb = [\s\S]*?;\n/) || [])[0];
    const measuredRows = paginatesByHeight(root);
    const entry = head(root, id) + `
import * as SJER from '${r}/src/components/SingleJobEstimateReport';
import { formatDDMMYYYY } from '${r}/src/lib/utils';
import { PrintableA4Page } from '${r}/src/components/LetterheadHeader';
${measuredRows ? `import { useMeasuredRowChunks } from '${r}/src/lib/useMeasuredRowChunks';
import { SHEET_MARK } from '${r}/src/lib/printOverflow';` : ''}
${hvSeAlOnly ? `import { HV_SE_NOT_APPLICABLE, HV_SE_WITH, HV_SE_WITHOUT, hvSeApplies, hvSeCell } from '${r}/src/lib/hvSeConductor';` : ''}
import { Printer, Download } from 'lucide-react';
const { classifyCoreType, classifyWindingMaterial } = SJER as any;
${hv || "const hvCoilsPerLimb = (coreType?: string): string => '4';   // absent at this commit"}
function Doc(): any {
  const isPrintOpen = true;
  const activeAgency: any = D.agency;
  const selectedMrNo: string = D.selectedMrNo;
  const internalInspectionDate: string = D.internalInspectionDate;
  // As the screen's mrJobs memo orders them: by job number, numerically.
  const mrJobs: any[] = [...D.mrJobs].sort((a: any, b: any) => String(a.jobNo).localeCompare(String(b.jobNo), undefined, { numeric: true }));
  const formsData: Record<string, any> = D.formsData;
  const handleExportExcel = () => {};
  const setIsPrintOpen = (_: boolean) => {};
${measuredRows ? `  // The deck cut by measured height, as the component calls it - see paginatesByHeight above for why it is here.
  const { chunks: jobChunks, offsets: chunkOffsets } = useMeasuredRowChunks(
    mrJobs, (job: any) => job.id, 'printable-internal-inspection-sheet', { enabled: true });` : ''}
  EXPECTED = { rows: mrJobs.length };
${block}
  return null;
}
` + mount + runtime('printable-internal-inspection-sheet', 'landscape', root);
    return { entry, coverageText: block + letterheadRegion(root) };
  },
});

/**
 * The external inspection sheet (AUDIT G102) - written inline inside its screen, like the internal one, and cut from
 * the source between markers. Its rows are read by the same `inspection` reader: its table carries a `Job No` header.
 */
const externalInspection = (id, title, select) => ({
  id, title, kind: 'inspection', container: 'printable-external-inspection-sheet', orientation: 'landscape',
  select,
  generate(root) {
    const r = slash(root);
    const file = 'src/components/ExternalInspection.tsx';
    // The whole print branch, from `if (isPrintOpen && selectedMrNo)` to the end of it. There is no scrap note here,
    // so the branch itself is the start - unlike the internal sheet.
    const block = cut(root, file, 'the external inspection sheet',
      '  if (isPrintOpen && selectedMrNo) {', '\n  return (\n    <div className="space-y-6 print:space-y-0">',
      ['<PrintableA4Page', '</PrintableA4Page>']);
    const measuredRows = paginatesByHeight(root);
    const entry = head(root, id) + `
import { formatDDMMYYYY } from '${r}/src/lib/utils';
import { PrintableA4Page } from '${r}/src/components/LetterheadHeader';
${measuredRows ? `import { useMeasuredRowChunks } from '${r}/src/lib/useMeasuredRowChunks';
import { SHEET_MARK } from '${r}/src/lib/printOverflow';` : ''}
import { Printer, Download } from 'lucide-react';
function Doc(): any {
  const isPrintOpen = true;
  const activeAgency: any = D.agency;
  const selectedMrNo: string = D.selectedMrNo;
  // As the screen's mrJobs memo orders them: by job number, numerically.
  const mrJobs: any[] = [...D.mrJobs].sort((a: any, b: any) => String(a.jobNo).localeCompare(String(b.jobNo), undefined, { numeric: true }));
  const formsData: Record<string, any> = D.formsData;
  const handleExportExcel = () => {};
  const setIsPrintOpen = (_: boolean) => {};
${measuredRows ? `  // The deck cut by measured height, as the component calls it - see paginatesByHeight above for why it is here.
  const { chunks: jobChunks, offsets: chunkOffsets } = useMeasuredRowChunks(
    mrJobs, (job: any) => job.id, 'printable-external-inspection-sheet', { enabled: true });` : ''}
  EXPECTED = { rows: mrJobs.length };
${block}
  return null;
}
` + mount + runtime('printable-external-inspection-sheet', 'landscape', root);
    return { entry, coverageText: block + letterheadRegion(root) };
  },
});

/**
 * The testing report (AUDIT G103). Its own row reader - `kind: 'testing'` - because its header is "Job No & S.No".
 *
 * ⚠ MORE STAND-INS THAN THE INSPECTION SHEETS NEED. `auth.currentUser?.displayName` prints inside the sign-off, and
 * rows fall back to the module-level `defaultTestingData`. Both are reconstructed here; `defaultTestingData` is cut
 * from the source rather than retyped, so a field added to it reaches this harness without anyone remembering to.
 */
const testingReport = (id, title, select) => ({
  id, title, kind: 'testing', container: 'printable-testing-sheet', orientation: 'landscape',
  select,
  generate(root) {
    const r = slash(root);
    const file = 'src/components/TestingReport.tsx';
    const block = cut(root, file, 'the testing report',
      '  if (isPrintOpen) {', '\n  return (\n    <div className="max-w-7xl mx-auto">',
      ['<PrintableA4Page', '</PrintableA4Page>']);
    const src = readSource(root, file);
    const defaults = (src.match(/const defaultTestingData: TestingData = \{[\s\S]*?\n\};\n/) || [])[0];
    if (!defaults) {
      throw new Refusal(`${file} no longer declares "const defaultTestingData: TestingData = {...};" - the testing report's rows fall back to it, so a harness without it would print blanks where the app prints values.`);
    }
    const measuredRows = paginatesByHeight(root);
    const entry = head(root, id) + `
import { formatDDMMYYYY } from '${r}/src/lib/utils';
import { PrintableA4Page } from '${r}/src/components/LetterheadHeader';
${measuredRows ? `import { useMeasuredRowChunks } from '${r}/src/lib/useMeasuredRowChunks';
import { SHEET_MARK } from '${r}/src/lib/printOverflow';` : ''}
import { Printer } from 'lucide-react';
type TestingData = any;
${defaults}
// The sign-off prints the signed-in user's display name; there is no sign-in here.
const auth: any = { currentUser: { displayName: 'print-check' } };
function Doc(): any {
  const isPrintOpen = true;
  const activeAgency: any = D.agency;
  const testingDate: string = D.testingDate;
  // ⚠ jobs AND selectedJobIds ARE SUPPLIED FOR BOTH SHAPES OF THE BRANCH. Before G103 the branch derived
  // selectedJobs itself from these two; from G103 the screen lifts that memo above its early return, so the
  // declaration moves HERE - and declaring it on a commit that still derives it inside would be a duplicate.
  const jobs: any[] = D.selectedJobs;
  const selectedJobIds = new Set<string>(D.selectedJobIds);
  const setIsPrintOpen = (_: boolean) => {};
  const handleExportExcel = () => {};
  const closePrint = () => {};
${measuredRows ? `  // As the screen's lifted memo orders them: by job number, numerically.
  const selectedJobs: any[] = [...D.selectedJobs].sort((a: any, b: any) => String(a.jobNo).localeCompare(String(b.jobNo), undefined, { numeric: true }));
  const { chunks: jobChunks, offsets: chunkOffsets } = useMeasuredRowChunks(
    selectedJobs, (job: any) => job.id, 'printable-testing-sheet', { seed: 8, enabled: true });` : ''}
  EXPECTED = { rows: D.selectedJobs.length };
${block}
  return null;
}
` + mount + runtime('printable-testing-sheet', 'landscape', root);
    return { entry, coverageText: block + letterheadRegion(root) };
  },
});

export const DOCUMENTS = [
  estimate('estimate-itemised', 'ITEMISED', 'Single-job estimate, itemised layout'),
  estimate('estimate-fixed-rate', 'FIXED_RATE', 'Single-job estimate, fixed-rate layout'),
  multiJob,
  inspection('inspection', 'Internal inspection sheet', live => pickInspection(live)),
  inspection('inspection-stress', 'Internal inspection sheet, longest real values in every row (the O58 case)', live => pickInspectionStress(live)),
  inspection('inspection-no-letterhead', 'Internal inspection sheet with the letterhead removed - the other end of the row-count range', live => pickInspectionNoLetterhead(live)),
  externalInspection('external-inspection', 'External inspection sheet', live => pickExternalInspection(live)),
  externalInspection('external-inspection-stress', 'External inspection sheet, longest real values in every row', live => pickExternalInspectionStress(live)),
  externalInspection('external-inspection-no-letterhead', 'External inspection sheet on an agency that has NO letterhead - a real agency, not a synthetic one', live => pickExternalInspection(live, { letterhead: false })),
  testingReport('testing', 'Testing report', live => pickTestingReport(live)),
  testingReport('testing-stress', 'Testing report, longest real values in every row', live => pickTestingReportStress(live)),
  testingReport('testing-no-letterhead', 'Testing report with the letterhead removed - the other end of the row-count range', live => pickTestingReportNoLetterhead(live)),
];

/** What the command line may name. */
export const ALIASES = {
  all: DOCUMENTS.map(d => d.id),
  estimate: ['estimate-itemised', 'estimate-fixed-rate'],
  'external': ['external-inspection', 'external-inspection-stress', 'external-inspection-no-letterhead'],
  'testing-report': ['testing', 'testing-stress', 'testing-no-letterhead'],
  ...Object.fromEntries(DOCUMENTS.map(d => [d.id, [d.id]])),
};
