// THE DOCUMENTS print-check KNOWS: how each is rendered, what it prints on, and how its rows are read.
//
// The two estimate layouts and the multi-job sheet are components and render directly. The inspection sheet is
// written inline inside its screen, and the multi-job sheet's figures come from functions inside EstimateGenerate -
// both are CUT from the source between markers (lib/sources.cut) until they are extracted.
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { slash } from './env.mjs';
import { cut, letterheadRegion, readSource } from './sources.mjs';
import { pickEstimate, pickInspection, pickMultiJob } from './data.mjs';

const EG = 'src/components/EstimateGenerate.tsx';

const head = (root, id) => `// GENERATED by scripts/print-check for one run - not edited, not kept.
import React from 'react';
import { createRoot } from 'react-dom/client';
import { MemoryRouter } from 'react-router-dom';
import './harness.css';
import { triggerUniversalPrint } from '${slash(root)}/src/lib/printUtils';
import DATA_ from './${id}.json';
const D: any = DATA_;
let EXPECTED: any = {};
(window as any).__printCheck = { state: 'rendering' };
`;

const mount = `createRoot(document.getElementById('root')!).render(<MemoryRouter><Doc /></MemoryRouter>);\n`;

/**
 * THE APP'S OWN PRINT PATH. triggerUniversalPrint writes the sheet into a new window; the window is captured instead
 * of opened, its one script (window.print on load) is dropped because printing is driven from outside, and the page
 * becomes that document. Everything else it writes is kept.
 */
const runtime = (container, orientation) => `
const w: any = window;
const sleep = (ms: number) => new Promise(r => setTimeout(r, ms));
(async () => {
  try {
    const t0 = Date.now();
    const lh = !!(D.agency && D.agency.letterheadUrl && (D.agency.letterheadMode === 'full_a4' || !D.agency.letterheadMode));
    let letterhead = lh ? 'pending' : 'none configured';
    for (;;) {
      const pages = document.querySelectorAll('.a4-print-page');
      const imgs = Array.from(document.querySelectorAll('.a4-print-page img')) as HTMLImageElement[];
      if (pages.length && (!lh || (imgs.length === pages.length && imgs.every(i => i.complete && i.naturalWidth > 0)))) { if (lh) letterhead = 'rendered'; break; }
      if (Date.now() - t0 > 30000) { if (!pages.length) throw new Error('no sheet rendered within 30s'); letterhead = 'NOT RENDERED within 30s'; break; }
      await sleep(200);
    }
    await (document as any).fonts.ready;
    await sleep(1200);
    let captured = '';
    const realOpen = window.open;
    (window as any).open = () => ({ document: { open() {}, write(s: string) { captured += s; }, close() {} } });
    await triggerUniversalPrint('${container}', 'print-check', 'print-check.pdf', '${orientation}');
    window.open = realOpen;
    if (captured.indexOf('${container}') === -1) throw new Error('the print window received nothing');
    const scripts = (captured.match(/<script>/g) || []).length;
    if (scripts !== 1) throw new Error('expected one script in the print window, found ' + scripts);
    document.open(); document.write(captured.replace(/<script>[\\s\\S]*?<\\/script>/, '')); document.close();
    const t1 = Date.now();
    for (;;) {
      const imgs = Array.from(document.images);
      const links = Array.from(document.querySelectorAll('link[rel="stylesheet"]')) as HTMLLinkElement[];
      if (imgs.every(i => i.complete) && links.every(l => l.sheet)) break;
      if (Date.now() - t1 > 15000) break;
      await sleep(100);
    }
    await sleep(500);
    w.__printCheck = { state: 'ready', letterhead, expected: EXPECTED, sheets: document.querySelectorAll('.a4-print-page').length };
  } catch (e: any) {
    w.__printCheck = { state: 'error', message: String((e && e.stack) || e) };
  }
})();
`;

const estimateSource = root => {
  const s = readSource(root, 'src/components/SingleJobEstimateReport.tsx');
  const a = s.indexOf('export default function SingleJobEstimateReport');
  return (a < 0 ? s : s.slice(a)) + letterheadRegion(root);
};

/** Both estimate layouts: the same component, a job whose tender prices it itemised, and one priced at a fixed rate. */
const estimate = (id, model, title) => ({
  id, title, kind: 'estimate', container: 'printable-estimate-container', orientation: 'portrait',
  select: live => pickEstimate(live, model),
  generate(root) {
    const r = slash(root);
    const orderRef = existsSync(join(root, 'src/lib/orderReference.ts'));   // G63; older commits have no such prop
    const entry = head(root, id) + `
import * as SJER from '${r}/src/components/SingleJobEstimateReport';
import * as AC from '${r}/src/lib/AgencyContext';
${orderRef ? `import { orderReferenceFor } from '${r}/src/lib/orderReference';` : ''}
const Estimate: any = (SJER as any).default;
function Doc(): any {
  const job = D.job, at = D.at, agency = D.agency;
  const est = (SJER as any).buildSingleJobEstimateData(job, agency, at, D.ext, D.int);
  EXPECTED = { rows: est.physicalItems.length + est.internalItems.length + est.labourItems.length };
  const extra: any = {};
  ${orderRef ? 'extra.orderRef = orderReferenceFor((AC as any).atResolutionForJob(job, D.ats), job.jobNo);' : ''}
  return (
    <div id="printable-estimate-container" className="space-y-6 print:space-y-0">
      <Estimate job={job} agency={agency} atMaster={at} externalData={D.ext} internalData={D.int} letterDateText={D.letterDate} {...extra} />
    </div>
  );
}
` + mount + runtime('printable-estimate-container', 'portrait');
    return { entry, coverageText: estimateSource(root) };
  },
});

const multiJob = {
  id: 'multi-job', title: 'Multi-job estimate sheet', kind: 'multi-job', container: 'printable-estimate-container', orientation: 'portrait',
  select: live => pickMultiJob(live),
  generate(root) {
    const r = slash(root);
    // THE SHEET'S FIGURES COME FROM EstimateGenerate'S OWN FUNCTIONS, CUT FROM ITS SOURCE. Re-implementing them here
    // would be a second pricing path - the defect G8 removed from this very sheet.
    const wrapper = cut(root, EG, "the multi-job sheet's pricing wrapper (getJobFullEstimate)",
      '  const getJobFullEstimate = (job: any) => {', '  const calculateJobTotal = (job: any) => {', ['getJobFullEstimatePure(']);
    const builders = cut(root, EG, "the multi-job sheet's data (builderLineFor, buildMultiJobData)",
      '  const estimateCache = new Map<string, any>();', '  // Helper to evaluate a job against Clause 4.0 Circle Estimate Power Limit',
      ['const builderLineFor = (', 'const buildMultiJobData = (mr: string) => {']);
    const sheet = readSource(root, 'src/components/MultiJobEstimateSheet.tsx');
    const entry = head(root, 'multi-job') + `
import { MultiJobEstimateSheet } from '${r}/src/components/MultiJobEstimateSheet';
import * as SJER from '${r}/src/components/SingleJobEstimateReport';
import * as AC from '${r}/src/lib/AgencyContext';
import * as estimateCalc from '${r}/src/lib/estimateCalc';
import * as scheduleItemMap from '${r}/src/lib/scheduleItemMap';
const { classifyWindingMaterial } = SJER as any;
const { getEstimateMasterForCore, atForJob } = AC as any;
const { getJobFullEstimate: getJobFullEstimatePure, isGpJob } = estimateCalc as any;
// Whichever of these the commit's cut code uses; the other is simply undefined.
const { lineForMasterRow, builderCodeForMasterRow } = scheduleItemMap as any;
function multiJobData(): any {
  const activeAgency = D.agency, atMasters = D.ats, activeAtMaster = D.at;
  const externalInspMap = D.ext, internalInspMap = D.int;
  const mrGroups: Record<string, any[]> = { [D.mrNo]: D.jobs };
  const estimableJobs = (mr: string) => (mrGroups[mr] || []).filter((j: any) => !isGpJob(j));
  const refNoText = D.refNo, currentSelectedDivision = D.division, signedByText = D.signedBy;
${wrapper}
${builders}
  return buildMultiJobData(D.mrNo);
}
function Doc(): any {
  const data = multiJobData();
  EXPECTED = { rowsPerSheet: data.items.length, columns: data.columns.length };
  return (
    <div id="printable-estimate-container" className="space-y-6 print:space-y-0">
      <MultiJobEstimateSheet agency={D.agency} data={data} />
    </div>
  );
}
` + mount + runtime('printable-estimate-container', 'portrait');
    const a = sheet.indexOf('export function MultiJobEstimateSheet');
    return { entry, coverageText: (a < 0 ? sheet : sheet.slice(a)) + letterheadRegion(root) };
  },
};

const inspection = {
  id: 'inspection', title: 'Internal inspection sheet', kind: 'inspection', container: 'printable-internal-inspection-sheet', orientation: 'landscape',
  select: live => pickInspection(live),
  generate(root) {
    const r = slash(root);
    const file = 'src/components/InternalInspection.tsx';
    // The whole print branch, from the scrap note it prints to the end of `if (isPrintOpen && selectedMrNo)`.
    const block = cut(root, file, 'the internal inspection sheet',
      '  const scrapJobs = mrJobs.filter(', '\n  return (\n    <div className="space-y-6 print:space-y-0">',
      ['if (isPrintOpen && selectedMrNo) {', '<PrintableA4Page', '</PrintableA4Page>']);
    const hv = (readSource(root, file).match(/const hvCoilsPerLimb = [\s\S]*?;\n/) || [])[0];
    const entry = head(root, 'inspection') + `
import * as SJER from '${r}/src/components/SingleJobEstimateReport';
import { formatDDMMYYYY } from '${r}/src/lib/utils';
import { PrintableA4Page } from '${r}/src/components/LetterheadHeader';
import { Printer, Download } from 'lucide-react';
const { classifyCoreType } = SJER as any;
${hv || "const hvCoilsPerLimb = (coreType?: string): string => '4';   // absent at this commit"}
function Doc(): any {
  const isPrintOpen = true;
  const activeAgency: any = D.agency;
  const selectedMrNo: string = D.selectedMrNo;
  const internalInspectionDate: string = D.internalInspectionDate;
  // As the screen's mrJobs memo orders them: by job number, numerically.
  const mrJobs: any[] = [...D.mrJobs].sort((a: any, b: any) => String(a.jobNo).localeCompare(String(b.jobNo), undefined, { numeric: true }));
  const formsData: Record<string, any> = D.formsData;
  const handleExportExcel = () => {};
  const setIsPrintOpen = (_: boolean) => {};
  EXPECTED = { rows: mrJobs.length };
${block}
  return null;
}
` + mount + runtime('printable-internal-inspection-sheet', 'landscape');
    return { entry, coverageText: block + letterheadRegion(root) };
  },
};

export const DOCUMENTS = [
  estimate('estimate-itemised', 'ITEMISED', 'Single-job estimate, itemised layout'),
  estimate('estimate-fixed-rate', 'FIXED_RATE', 'Single-job estimate, fixed-rate layout'),
  multiJob,
  inspection,
];

/** What the command line may name. */
export const ALIASES = {
  all: DOCUMENTS.map(d => d.id),
  estimate: ['estimate-itemised', 'estimate-fixed-rate'],
  ...Object.fromEntries(DOCUMENTS.map(d => [d.id, [d.id]])),
};
